inherit_from:
  - .rubocop_todo.yml
  - config/rubocop/rubocop.yml
  - config/rubocop/rails.yml
  - config/rubocop/rspec.yml

# 以下を参考
# https://github.com/onk/onkcop/blob/master/config/rubocop.yml
require:
  - rubocop-rails
  - rubocop-rspec


