version: '3.3'
services:
  web: &web
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      REDIS_URL: redis://redis:6379
      DISABLE_BASIC_AUTH: disable
      RAILS_MASTER_KEY: abcd1234
      DATABASE_URL: postgres://postgres:@db:5432
      USE_LOCAL_STORAGE: "yes"
    ports:
      - ${PORT:-3000}:3000
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
      - bundle:/var/bundle
      - node_modules:/app/node_modules
      - binstubs:/var/binstubs
      - storage:/app/storage

  worker:
    <<: *web
    restart: always
    command: sidekiq
    ports: []
    depends_on:
      - web

  db:
    image: postgres:12-alpine
    restart: always
    # ports:
    #   - 15432:5432
    environment:
      TZ: "Asia/Tokyo"
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_USER: postgres
    volumes:
      - db:/var/lib/postgresql/data

  redis:
    image: redis:5-alpine
    restart: always
    # ports:
    #   - 16379:6379
    volumes:
      - redis:/data

volumes:
  db:
  redis:
  storage:
  bundle:
  node_modules:
  binstubs:
