
version: 2.1

executors:
  default:
    docker:
      - image: circleci/ruby:2.6.6-node-browsers
      - image: circleci/postgres:11.4-alpine-ram
        environment:
          POSTGRES_USER: circleci
          POSTGRES_DB: playground_test
      - image: circleci/redis:5.0.5-alpine
    environment:
      BUNDLE_JOBS: 4
      BUNDLE_RETRY: 4
      BUNDLE_PATH: vendor/bundle
      BUNDLER_VERSION: 2.1.4
      RAILS_ENV: test
      RACK_ENV: test
      PGHOST: localhost
      DATABASE_URL: postgres://localhost:5432

jobs:
  bundle:
    executor: default
    steps:
      - checkout
      - run: gem install bundler --version "$BUNDLER_VERSION"
      - restore_cache:
          keys:
            - bundler-{{ arch }}-{{ checksum "Gemfile.lock" }}
      - run: bundle check || bundle install  --clean --deployment
      - save_cache:
          key: bundler-{{ arch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - persist_to_workspace:
          root: .
          paths:
            - vendor/bundle
  yarn:
    executor: default
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-{{ arch }}-{{ checksum "yarn.lock" }}
      - run: yarn install
      - save_cache:
          key: yarn-{{ arch }}-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
      - persist_to_workspace:
          root: .
          paths:
            - node_modules
  compile:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: gem install bundler --version "$BUNDLER_VERSION"
      - run: bundle check || bundle install  --clean --deployment
      - run: bundle exec rails webpacker:compile
      - persist_to_workspace:
          root: .
          paths:
            - tmp/cache/webpacker
            - public/packs*
  eslint:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: yarn run lint
  jest:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          command: yarn run test
  rubocop:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: gem install bundler --version "$BUNDLER_VERSION"
      - run: bundle check || bundle install  --clean --deployment
      - run:
          command: bundle exec rubocop --format progress --format html --out tmp/rubocop.html
      - store_artifacts:
          path: tmp/rubocop.html
          destination: rubocop.html
  rspec:
    executor: default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: gem install bundler --version "$BUNDLER_VERSION"
      - run: bundle check || bundle install  --clean --deployment
      - run: dockerize -wait tcp://localhost:6379 -timeout 2m # Redis
      - run: dockerize -wait tcp://localhost:5432 -timeout 2m # Postgres
      - run: bundle exec rails db:create db:migrate RAILS_ENV=test
      - run:
          command: |
            bundle exec rspec \
              --profile \
              --format RspecJunitFormatter \
              --out tmp/results/rspec.xml \
              --format progress \
              $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split)
      - store_test_results:
          path: tmp/results
      - store_artifacts:
          path: coverage
          destination: coverage
      - store_artifacts:
          path: tmp/screenshots
          destination: screenshots
      - store_artifacts:
          path: log
          destination: log
workflows:
  version: 2.1
  build:
    jobs:
      - bundle
      - yarn
      - compile:
          requires:
            - bundle
            - yarn
      - rspec:
          requires:
            - compile
      - rubocop:
          requires:
            - bundle
      - eslint:
          requires:
            - yarn
      - jest:
          requires:
            - yarn
