default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV.fetch('DATABASE_URL','postgres://postgres:@db') %>

development:
  <<: *default
  database: <%= ENV.fetch('DATABASE_BASENAME', '108sharing') + '_development' %>

test:
  <<: *default
  database: <%= ENV.fetch('DATABASE_BASENAME', '108sharing') + '_test' %>

production:
  <<: *default
  database: <%= ENV['DATABASE_NAME'] || '108sharing_production' %>
  username: <%= ENV['DATABASE_USER'] || '108sharing' %>
  password: <%= ENV['DATABASE_PASS'] || '' %>
  url: <%= ENV['DATABASE_URL'] %>
